### ISSUE TITLE
problem using monetary

### ISSUE THREAD

**Issue by plentz** [sevenwire/forgery#38]
Works in 0.3.12, breaks in 0.4.2.

```
Forgery(:monetary).money

     NoMethodError:
       undefined method `random' for 0..1000:Range
```
