### ISSUE TITLE
Regression in Forgery::Name.first_name as of v0.4.0?

### ISSUE THREAD

**Issue by todc** [sevenwire/forgery#36]
Looks like the `random` method is getting called twice in [`Forgery::Name.first_name`](https://github.com/sevenwire/forgery/blob/master/lib/forgery/forgery/name.rb#L8), causing an `undefined method 'random'` exception.

Affects v0.4.0. Was previously working in v0.3.12.
